### ISSUE TITLE
Is there an option similar to Babel's importSource for automatic jsx transformation

### ISSUE THREAD

**Issue by zeljkocurcic** [privatenumber/esbuild-loader-examples#8]
### Feature request

Is there a possibility to do something like this with esbuild-loader:

```
['@babel/preset-react', {
  runtime: 'automatic',
  development: process.env.NODE_ENV === 'development',
  importSource: '@welldone-software/why-did-you-render',
}]
```

### Motivations

This is needed to support why-did-you-render when using automatic JSX transformation

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
I think this is answered in the esbuild docs.

Closing as Issues is not a place for Q&A
